### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by XhmikosR** [libreops/libredns.gr#1]
* use packages from npm instead of lib
* use sass and extend Bootstrap's Sass; this will allow you to just include what you need
* remove font awesome and just use an SVG; you only use one icon
* use purgecss
* optimize images
* generate proper favicons for all platforms (I need the logo as an SVG, preferably square)

427 for a single page seems a lot; we can definitely do a lot better :)

PS. I could probably take a stab at it later and make a branch with separate patches with my suggestions.

**Comment by comzeradd** [comment]
Ah, we forgot to hide the issues tab here :) This is just mirroring the [main repo](https://gitlab.com/libreops/libredns/libredns.gr). But it's ok for now.

So yes, some of these are low hanging fruits and can be easily done. Some need a bit more time.

I didn't get one thing though:

> use packages from npm instead of lib

The packages inside lib are coming from npm. We just run `gulp assets` to move the relevant bits there so we don't need to have the `node_modules` folder on production.

**Comment by XhmikosR** [comment]
> The packages inside lib are coming from npm. We just run gulp assets to move the relevant bits there so we don't need to have the node_modules folder on production.

Then, shouldn't the lib folder be in .gitignore?

I could probably submit a few PRs in the next days to the main repo.

**Comment by XhmikosR** [comment]
Feel free to move this issue to the gitlab repo :)

Here's a first draft of my patch https://gtmetrix.com/compare/1C9WPZhf/ppEJR9iQ

I will need some help with the folder structure and the favicon, but the savings are more than 50%

**Comment by comzeradd** [comment]
> > The packages inside lib are coming from npm. We just run gulp assets to move the relevant bits there so we don't need to have the node_modules folder on production.
> 
> Then, shouldn't the lib folder be in .gitignore?

No, because we don't run `npm i` on production, we just clone whatever is on the repo. So we check-in the specific files we use from these libraries. Once we put this on CI we can definitely gitignore these files.

**Comment by XhmikosR** [comment]
Closing this since I don't think I'll find any time soon to finish my patch.
